//main
export const MAIN_CHANGE_OPTION = 'MAIN_CHANGE_OPTION';
export const MAIN_TOGGLE_OPTION = 'MAIN_TOGGLE_OPTION';

//process
export const PROCESS_START_CRAWLING = 'PROCESS_START_CRAWLING';
export const PROCESS_ADD_CRAWLING_LEVEL = 'PROCESS_ADD_CRAWLING_LEVEL';
export const PROCESS_UPDATE_CRAWLING_LEVEL_STATUS = 'PROCESS_UPDATE_CRAWLING_LEVEL_STATUS';
export const PROCESS_START_PARSING = 'PROCESS_START_PARSING';
export const PROCESS_UPDATE_PARSING_STATUS = 'PROCESS_UPDATE_PARSING_STATUS';

//results
export const RESULT_SHOW = 'RESULT_SHOW';
export const RESULT_TOGGLE_COUNTRY = 'RESULT_TOGGLE_COUNTRY';

//update
export const UPDATE_CHANGE_STATE = 'UPDATE_CHANGE_STATE';
export const UPDATE_UP_DOWNLOAD_PROGRESS = 'UPDATE_UP_DOWNLOAD_PROGRESS';
export const UPDATE_CLOSE = 'UPDATE_CLOSE';

// process + results
export const CLOSE = 'CLOSE';
